namespace KeryxPars.HL7.Definitions;

using KeryxPars.HL7.Attributes;
using KeryxPars.HL7.Segments;

/// <summary>
/// Default HL7 message implementation with comprehensive segment support.
/// Previously known as HL7Message - this is the general-purpose message class
/// that supports all common HL7 segments for ADT, medication orders, and other message types.
/// AddSegment() method is automatically generated by source generator.
/// </summary>
[GenerateSegmentHandlers]
public partial class HL7DefaultMessage : HL7BaseMessage
{
    public PV1? Pv1 { get; set; }
    public PV2? Pv2 { get; set; }

    // Repeatable segments
    public List<AL1> Allergies { get; set; } = [];
    public List<DG1> Diagnoses { get; set; } = [];
    public List<IN1> Insurance { get; set; } = [];
    
    [IgnoreSegment] // Orders are complex groups, handled manually
    public List<OrderGroup> Orders { get; set; } = [];

    /// <summary>
    /// Adds an order group to the message.
    /// Virtual to allow derived classes to customize behavior.
    /// </summary>
    public override void AddOrderGroup(OrderGroup orderGroup)
    {
        Orders.Add(orderGroup);
    }
}


