namespace KeryxPars.HL7.Definitions;

using KeryxPars.HL7.Attributes;
using KeryxPars.HL7.Segments;

/// <summary>
/// Specialized HL7 message for laboratory orders and results.
/// Supports ORU (observation result) and ORM (order) message types.
/// AddSegment() method is automatically generated by source generator.
/// </summary>
[GenerateSegmentHandlers]
public partial class LabMessage : HL7BaseMessage
{
    public PV1? Pv1 { get; set; }
    public PV2? Pv2 { get; set; }

    /// <summary>
    /// Lab orders with associated OBR/OBX segments
    /// </summary>
    [IgnoreSegment] // Complex order groups handled manually
    public List<OrderGroup> Orders { get; set; } = [];

    /// <summary>
    /// Specimen information for lab orders
    /// </summary>
    public List<SPM> Specimens { get; set; } = [];

    /// <summary>
    /// Specimen container details
    /// </summary>
    public List<SAC> Containers { get; set; } = [];

    /// <summary>
    /// Clinical trial identification for research labs
    /// </summary>
    public List<CTI> ClinicalTrials { get; set; } = [];

    /// <summary>
    /// Diagnoses relevant to lab orders
    /// </summary>
    public List<DG1> Diagnoses { get; set; } = [];

    /// <summary>
    /// Notes and comments for lab orders/results
    /// </summary>
    public List<NTE> Notes { get; set; } = [];

    /// <summary>
    /// Adds an order group to the message.
    /// </summary>
    public override void AddOrderGroup(OrderGroup orderGroup)
    {
        Orders.Add(orderGroup);
    }
}


